# Generated by Django 5.2.4 on 2025-08-04 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('ph', 'PH'), ('oficina', 'Oficina'), ('cochera', 'Cochera'), ('local', 'Local'), ('terreno', 'Terreno'), ('galpon', 'Galpón'), ('campo', 'Campo'), ('otros', 'Otros')], max_length=20)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(default='Buenos Aires', max_length=100)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('superficie_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banios', models.IntegerField(blank=True, null=True)),
                ('cocheras', models.IntegerField(blank=True, null=True)),
                ('acepta_mascotas', models.BooleanField(default=False)),
                ('tipo_mascota_permitida', models.CharField(choices=[('perros', 'Perros'), ('gatos', 'Gatos'), ('ambos', 'Perros y Gatos'), ('no_especificado', 'No especificado')], default='no_especificado', max_length=30)),
                ('is_destacada', models.BooleanField(default=False)),
                ('estado_publicacion', models.CharField(choices=[('publicada', 'Publicada'), ('borrador', 'Borrador')], default='publicada', max_length=20)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='web_app.propiedad')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/galeria/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='web_app.propiedad')),
            ],
        ),
    ]
