# Generated by Django 5.2.4 on 2025-08-05 14:01

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno'), ('local', 'Local/Oficina')], max_length=20)),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('alquiler', 'Alquiler')], max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('superficie_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banios', models.IntegerField(blank=True, null=True)),
                ('cocheras', models.IntegerField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(help_text='Imagen destacada de la propiedad. Se sube a S3.', storage=storages.backends.s3.S3Storage(), upload_to='propiedades/')),
                ('is_destacada', models.BooleanField(default=False)),
                ('estado_publicacion', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('vendida', 'Vendida'), ('alquilada', 'Alquilada')], default='borrador', max_length=20)),
                ('acepta_mascotas', models.BooleanField(default=False)),
                ('tipo_mascota_permitida', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='propiedades/galeria/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='web_app.propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de la Propiedad',
                'verbose_name_plural': 'Imágenes de la Propiedad',
            },
        ),
    ]
